### PR TITLE
This will add a directory

### PR DESCRIPTION
**Pull request by Fastidious**

### CODE REVIEW

**Comment by yabobay** [comment]
I don't get it. What is it?

**Comment by Fastidious** [comment]
If you accept this pull request, it will add a `test` directory, will will make your site URL look like this: https://yabobay.github.io/test/. That is what you were looking for the other day in IRC, correct?

**Comment by Fastidious** [comment]
You figured out what you wanted to do, this PR no longer applies. Cheers!

**Comment by yabobay** [comment]
Oh! You're from the IRC I asked about stuff on? If you have the same username on there, then sorry, I don't really pay attention to usernames. I was really confused as to what your PR was for, for a sec.
Well thanks for trying to help, on here and on there.

**Pull request closed without merging**
